apiVersion: apps/v1
kind: Deployment
metadata:
  name: apple
  labels:
    apps: apple
  namespace: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      component: apple
  template:
    metadata:
      labels:
        component: apple
    spec:
      containers:
      - name: apple
        image: dapoajuwon/go-api:latest
        imagePullPolicy: Always
        resources: 
          requests:
            memory: "128Mi" #default 256Mi
        ports:
          - containerPort: 3000  
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: apple
  annotations:
    kubernetes.io/ingress.class: "nginx" #nginx / prod-nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2 
  labels:
    app: apple
  namespace: prod
spec:
  rules:
    - http:
        paths:
        - path: /apple(/|$)(.*)
          backend:
            serviceName: apple
            servicePort: 3001

---
apiVersion: v1
kind: Service
metadata:
  name: apple
  labels:
    app: apple
    service: apple
  namespace: prod
spec:
  type: ClusterIP
  selector:
    component: apple
  ports:
  - name: apple
    port: 3001
    targetPort: 3000
    