apiVersion: apps/v1
kind: Deployment
metadata:
  name: webinar
  labels:
    apps: wallet
  namespace: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      component: webinar
  template:
    metadata:
      labels:
        component: webinar
    spec:
      containers:
      - name: webinar
        image: dapoajuwon/ekswebinar:latest
        imagePullPolicy: Always
        resources: 
          requests:
            memory: "128Mi" #default 256Mi
        ports:
          - containerPort: 3000   
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: webinar
  annotations:
    kubernetes.io/ingress.class: "nginx" #nginx / prod-nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2 
  labels:
    app: webinar
  namespace: prod
spec:
  rules:
    - http:
        paths:
        - path: /webinar(/|$)(.*)
          backend:
            serviceName: webinar
            servicePort: 4000

---
apiVersion: v1
kind: Service
metadata:
  name: webinar
  labels:
    app: webinar
    service: webinar
  namespace: prod
spec:
  type: ClusterIP
  selector:
    component: webinar
  ports:
  - name: webinar
    port: 4000
    targetPort: 3000
    